/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <stdio.h>
int main () {
    int sum = 0;
    int currentNumber = 2;
    int lastnumber = 1;
    int fibonacci = 0;

    while(fibonacci <= 4000000)
    {
        fibonacci = currentNumber + lastnumber; //3
        lastnumber = currentNumber; //neue letzte zahl
        currentNumber = fibonacci; //neue Fibonacci zahl
        printf("fibo: %d\n",fibonacci);
        if(fibonacci %2 == 0) {
            sum = sum + fibonacci;
        }
    }

    printf("\n\nSum of all previous fibos: %d\n",sum);
}
